<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />
	<Import Project="..\..\..\packing.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Volo.Abp.Ddd.Application" />
		<PackageReference Include="Volo.Abp.Identity.Application.Contracts" />
		<ProjectReference Include="..\Syrna.QuartzAdmin.Application.Contracts\Syrna.QuartzAdmin.Application.Contracts.csproj" />
		<ProjectReference Include="..\Syrna.QuartzAdmin.Domain\Syrna.QuartzAdmin.Domain.csproj" />
	</ItemGroup>

</Project>
