<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />
	<Import Project="..\..\..\configureawait.props" />
	<Import Project="..\..\..\packing.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Syrna\QuartzAdmin\Triggers\TriggerType.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Quartz" />
		<PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
		<PackageReference Include="Volo.Abp.Authorization" />
		<PackageReference Include="CronExpressionDescriptor" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Syrna.QuartzAdmin.Domain.Shared\Syrna.QuartzAdmin.Domain.Shared.csproj" />
	</ItemGroup>

</Project>
