<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<Import Project="..\..\..\..\common.props" />
	<Import Project="..\..\..\..\configureawait.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
		<LangVersion>latest</LangVersion>
		<DebuggerSupport>true</DebuggerSupport>
		<CopyOutputSymbolsToPublishDirectory>true</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Components\CustomUserMenu.razor.cs" />
	  <Compile Remove="RemoteExternalLocalizationStore.cs" />
	  <Compile Remove="UserExceptionInformer.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="Components\CustomUserMenu.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazorise.Bootstrap5" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" />
		<PackageReference Include="Blazorise.Charts" />
		
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" />
		<!--<PackageReference Include="System.Net.Http.Json" />-->
		<PackageReference Include="Blazored.LocalStorage" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Volo.Abp.Autofac.WebAssembly" />
		<PackageReference Include="Volo.Abp.SettingManagement.Application.Contracts" />
		
		<PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme" />
		<PackageReference Include="Volo.Abp.Identity.Blazor.WebAssembly" />
		<PackageReference Include="Volo.Abp.TenantManagement.Blazor.WebAssembly" />
		<PackageReference Include="Volo.Abp.SettingManagement.Blazor.WebAssembly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Syrna.QuartzAdmin.MainDemo.Blazor.WebAssembly\Syrna.QuartzAdmin.MainDemo.Blazor.WebAssembly.csproj" />
		<ProjectReference Include="..\..\src\Syrna.QuartzAdmin.MainDemo.HttpApi.Client\Syrna.QuartzAdmin.MainDemo.HttpApi.Client.csproj" />
		<ProjectReference Include="..\..\src\Syrna.QuartzAdmin.MainDemo.Jobs\Syrna.QuartzAdmin.MainDemo.Jobs.csproj" />
	</ItemGroup>

</Project>
